### ISSUE TITLE
求助：在Android 7.0系统上， 将一个Dex通过classloader加载到主应用。 这个Dex中包含一个class，一个interface 。 当这个Dex被加载后，class的使用没有任何问题，但是interface只能直接初始化，并调用其函数。无法将其实例通过函数传参形式传递到另一个类中使用（其中也不能将其传递到和它同在一个Dex的class使用），否则就会报错。另外，如果将上述报错代码放到Handler或新起一个线程，也没有问题。

### ISSUE THREAD

**Issue by Hyj06** [Hyj06/DexLoader_Issues#2]
**报错堆栈**

            2022-11-06 11:35:07.860 31825-31825/lx.sdk.api.lib.demo I/art: Rejecting re-init on previously-failed class java.lang.Class<lx.sdk.api.lib.demo.DemoApplication$1>: java.lang.NoClassDefFoundError: Failed resolution of: Llx/sdk/tools/log/HApi_1;
              2022-11-06 11:35:07.860 31825-31825/lx.sdk.api.lib.demo I/art: at java.lang.Object java.lang.Class.newInstance!() (Class.java:-2)
              2022-11-06 11:35:07.860 31825-31825/lx.sdk.api.lib.demo I/art: at android.app.Application android.app.Instrumentation.newApplication(java.lang.Class, android.content.Context) (Instrumentation.java:1007)
              2022-11-06 11:35:07.860 31825-31825/lx.sdk.api.lib.demo I/art: at android.app.Application android.app.Instrumentation.newApplication(java.lang.ClassLoader, java.lang.String, android.content.Context) (Instrumentation.java:992)
              2022-11-06 11:35:07.860 31825-31825/lx.sdk.api.lib.demo I/art: at android.app.Application android.app.LoadedApk.makeApplication(boolean, android.app.Instrumentation) (LoadedApk.java:801)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5564)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at void android.app.ActivityThread.-wrap2(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1629)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:110)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at void android.os.Looper.loop() (Looper.java:203)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6337)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1084)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:945)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "lx.sdk.tools.log.HApi_1" on path: DexPathList[[zip file "/data/app/lx.sdk.api.lib.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/lx.sdk.api.lib.demo-1/lib/arm, /data/app/lx.sdk.api.lib.demo-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at java.lang.Object java.lang.Class.newInstance!() (Class.java:-2)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at android.app.Application android.app.Instrumentation.newApplication(java.lang.Class, android.content.Context) (Instrumentation.java:1007)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at android.app.Application android.app.Instrumentation.newApplication(java.lang.ClassLoader, java.lang.String, android.content.Context) (Instrumentation.java:992)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at android.app.Application android.app.LoadedApk.makeApplication(boolean, android.app.Instrumentation) (LoadedApk.java:801)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5564)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at void android.app.ActivityThread.-wrap2(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1629)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:110)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at void android.os.Looper.loop() (Looper.java:203)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6337)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1084)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo I/art: at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:945)
              2022-11-06 11:35:07.861 31825-31825/lx.sdk.api.lib.demo D/AndroidRuntime: Shutting down VM
              2022-11-06 11:35:07.863 31825-31825/lx.sdk.api.lib.demo E/AndroidRuntime: FATAL EXCEPTION: main
              Process: lx.sdk.api.lib.demo, PID: 31825
              java.lang.NoClassDefFoundError: Failed resolution of: Llx/sdk/tools/log/HApi_1;
              at java.lang.Class.newInstance(Native Method)
              at android.app.Instrumentation.newApplication(Instrumentation.java:1007)
              at android.app.Instrumentation.newApplication(Instrumentation.java:992)
              at android.app.LoadedApk.makeApplication(LoadedApk.java:801)
              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5564)
              at android.app.ActivityThread.-wrap2(ActivityThread.java)
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1629)
              at android.os.Handler.dispatchMessage(Handler.java:110)
              at android.os.Looper.loop(Looper.java:203)
              at android.app.ActivityThread.main(ActivityThread.java:6337)
              at java.lang.reflect.Method.invoke(Native Method)
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
              Caused by: java.lang.ClassNotFoundException: Didn't find class "lx.sdk.tools.log.HApi_1" on path: DexPathList[[zip file "/data/app/lx.sdk.api.lib.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/lx.sdk.api.lib.demo-1/lib/arm, /data/app/lx.sdk.api.lib.demo-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
              at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
              at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
              at java.lang.Class.newInstance(Native Method)
              at android.app.Instrumentation.newApplication(Instrumentation.java:1007)
              at android.app.Instrumentation.newApplication(Instrumentation.java:992)
              at android.app.LoadedApk.makeApplication(LoadedApk.java:801)
             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5564)
              at android.app.ActivityThread.-wrap2(ActivityThread.java)
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1629)
              at android.os.Handler.dispatchMessage(Handler.java:110)
              at android.os.Looper.loop(Looper.java:203)
              at android.app.ActivityThread.main(ActivityThread.java:6337)
              at java.lang.reflect.Method.invoke(Native Method)
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
              2022-11-06 11:35:07.867 31825-31841/lx.sdk.api.lib.demo W/SQLiteConnection: Could not change the database journal as DB was busy. Proceeding...
              2022-11-06 11:35:07.868 996-1199/? W/ActivityManager: Force finishing activity lx.sdk.api.lib.demo/.DemoActivity
              2022-11-06 11:35:07.871 996-1199/? V/WindowManager: findFocusedWindow: No focusable windows.
              2022-11-06 11:35:07.872 996-1199/? W/WindowManager: updateLightNavigationBarLw--imeWin:null
              2022-11-06 11:35:07.872 996-1199/? W/WindowManager: updateLightNavigationBarLw--navColorWin:Window{3bb6178 u0 Starting lx.sdk.api.lib.demo}
              2022-11-06 11:35:07.873 996-31842/? D/AES: onEndOfErrorDumpThread: data_app_crash Process: lx.sdk.api.lib.demo
              Flags: 0x38e8bf46
             Package: lx.sdk.api.lib.demo v1 (1.0)
              Foreground: Yes
              Build: alps/full_rlk6580_we_c_m/rlk6580_we_c_m:7.1.1/N6F26Q/660:user/release-keys
              java.lang.NoClassDefFoundError: Failed resolution of: Llx/sdk/tools/log/HApi_1;
              at java.lang.Class.newInstance(Native Method)
              at android.app.Instrumentation.newApplication(Instrumentation.java:1007)
              at android.app.Instrumentation.newApplication(Instrumentation.java:992)
              at android.app.LoadedApk.makeApplication(LoadedApk.java:801)
              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5564)
              at android.app.ActivityThread.-wrap2(ActivityThread.java)
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1629)
              at android.os.Handler.dispatchMessage(Handler.java:110)
              at android.os.Looper.loop(Looper.java:203)
              at android.app.ActivityThread.main(ActivityThread.java:6337)
              at java.lang.reflect.Method.invoke(Native Method)
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
              Caused by: java.lang.ClassNotFoundException: Didn't find class "lx.sdk.tools.log.HApi_1" on path: DexPathList[[zip file "/data/app/lx.sdk.api.lib.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/lx.sdk.api.lib.demo-1/lib/arm, /data/app/lx.sdk.api.lib.demo-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
              at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
              at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
              at java.lang.Class.newInstance(Native Method)
              at android.app.Instrumentation.newApplication(Instrumentation.java:1007)
              at android.app.Instrumentation.newApplication(Instrumentation.java:992)
              at android.app.LoadedApk.makeApplication(LoadedApk.java:801)
              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5564)
              at android.app.ActivityThread.-wrap2(ActivityThread.java)
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1629)
              at android.os.Handler.dispatchMessage(Handler.java:110)
              at android.os.Looper.loop(Looper.java:203)
              at android.app.ActivityThread.main(ActivityThread.java:6337)
              at java.lang.reflect.Method.invoke(Native Method)
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
              31825

**HApi_1.java 代码**

      public interface HApi_1 {
          void v(String var1, String var2);
      
          void d(String var1, String var2);
      
         void i(String var1, String var2);
      
         void w(String var1, String var2);
      
          void e(String var1, String var2);
      
          void e(String var1, String var2, Throwable var3);
      }

MyLogUtils.java 代码

      public class MyLogUtils {
          static HApi_1 logger;
          
          public static void init(boolean var0, HApi_1 var1) {
              logger = var1;
          }
      
          public static void v(String var0, String var1) {
              if (null != logger) logger.v(var0, var1);
          }
      }

**Comment by Hyj06** [comment]
**报错代码**

        public void onCreate() {
        super.onCreate();
        String dexPath = "/sdcard/dex_tst/new_tool.dex";
        DexManager.fixE(this, dexPath, "dexPath");
        HApi_1 logger = new HApi_1() {
            @Override
            public void v(String s, String s1) {
                System.out.println("HApi_1 " + s + s1);
            }

            @Override
            public void d(String s, String s1) {

            }

            @Override
            public void i(String s, String s1) {

            }

            @Override
            public void w(String s, String s1) {

            }

            @Override
            public void e(String s, String s1) {

            }

            @Override
            public void e(String s, String s1, Throwable throwable) {

            }
        };

        // TODO --- 直接调用，不会报错
        logger.v("测试日志 > ", " 测试数据 ... ");

        // TODO --- 将logger作为函数传参，就会报错;
        MyLogUtils.init(true, logger);
    }

**Comment by Hyj06** [comment]
**将代码放在 Handler 或 新线程 中，也没有问题**
   
    @Override
    public void onCreate() {
        super.onCreate();
        instance = this;
        String dexPath = "/sdcard/dex_tst/new_tool.dex";
        DexManager.fixE(this, dexPath, "dexPath");
        
        // TODO --- 将代码整体放入 Handler 或 新线程 中，可正常被调用
        new Handler().post(new Runnable() {
            @OverRide
            public void run() {
                HApi_1 logger = new HApi_1() {
                    @OverRide
                    public void v(String s, String s1) {
                        System.out.println("HApi_1 " + s + s1);
                    }

                    @Override
                    public void d(String s, String s1) {

                    }

                    @Override
                    public void i(String s, String s1) {

                    }

                    @Override
                    public void w(String s, String s1) {

                    }

                    @Override
                    public void e(String s, String s1) {

                    }

                    @Override
                    public void e(String s, String s1, Throwable throwable) {

                    }
                };

                logger.v("测试日志 > ", " 测试数据 ... ");

                MyLogUtils.init(true, logger);
            }
        });
    }

**Comment by nkbai** [comment]
DexManager 哪里来的？

**Comment by Hyj06** [comment]
public class DexManager {
    
    /**
     * 补丁dex文件解压后的位置
     *
     * @param context
     * @return
     */
    public static String getOptimizedDirectory(Context context, String dirTag) {
        return ShellDirectoryUtils.getOptimizedDirectory(context).getAbsolutePath();
    }

    /**
     * 热修复辅助方法
     *
     * @param context
     */
    public static void fixE(Context context, String dexInternalPath, String dirTag) {
        File dexFile = new File(dexInternalPath);
        Log.e("dex fix ", "dexInternalPath = " + dexInternalPath + " , dexFile.exists() = " + dexFile.exists());
        fix(context, dexFile.getAbsolutePath(), getOptimizedDirectory(context, dirTag));
    }

    /**
     * 热修复
     *
     * @param context
     * @param dexPath
     * @param optimizedDirectory
     */
    private static void fix(Context context, String dexPath, String optimizedDirectory) {
        System.out.println("dexPath = " + dexPath + " > " + new File(dexPath).exists() + " , optimizedDirectory = " + optimizedDirectory);
        if (TextUtils.isEmpty(dexPath) || TextUtils.isEmpty(optimizedDirectory)) {
            throw new NullPointerException("The argument dexPath or optimizedDirectory is null");
        }

        try {
            // DexPathList类有一个私有的成员变量：Element[] dexElements，这个数组就是用来存放dex和resource文件实例的
            PathClassLoader pathClassLoader = (PathClassLoader) context.getClassLoader();
            ElementWrapper dexElementsOld = getElements(pathClassLoader);

            // DexClassLoader的父类也是BaseDexClassLoader
            DexClassLoader dexClassLoader = new DexClassLoader(dexPath, optimizedDirectory, null, context.getClassLoader());
            // 获取补丁的dexElements数组实例
            ElementWrapper dexElementsNew = getElements(dexClassLoader);

            int oldDexElementsLen = Array.getLength(dexElementsOld.dexElements);
            int newDexElementsLen = Array.getLength(dexElementsNew.dexElements);
            Object newElements = Array.newInstance(Array.get(dexElementsOld.dexElements, 0).getClass(), oldDexElementsLen + newDexElementsLen);
            for (int i = 0; i < oldDexElementsLen; i++) {
                Array.set(newElements, i, Array.get(dexElementsNew.dexElements, i));
            }
            for (int i = 0; i < newDexElementsLen; i++) {
                Array.set(newElements, i + oldDexElementsLen, Array.get(dexElementsOld.dexElements, i));
            }
            dexElementsOld.dexElementsField.set(dexElementsOld.dexPathList, newElements);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static ElementWrapper getElements(BaseDexClassLoader baseDexClassLoader) {
        ElementWrapper elementWrapper = null;
        try {
            Class<?> baseDexClassLoaderClass = baseDexClassLoader.getClass().getSuperclass();
            Field dexPathListField = baseDexClassLoaderClass.getDeclaredField("pathList");
            dexPathListField.setAccessible(true);
            // DexPathList的实例
            Object dexPathList = dexPathListField.get(baseDexClassLoader);
            // 获得DexPathList的Class，从而通过反射获得它的成员变量dexElements
            Class<?> dexPathListClass = dexPathListField.getType();
            Field dexElementsField = dexPathListClass.getDeclaredField("dexElements");
            dexElementsField.setAccessible(true);
            elementWrapper = new ElementWrapper();
            elementWrapper.dexPathList = dexPathList;
            elementWrapper.dexElementsField = dexElementsField;
            // 获取dexElements数组实例
            elementWrapper.dexElements = dexElementsField.get(dexPathList);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return elementWrapper;
    }

    private static class ElementWrapper {
        Object dexPathList;
        Object dexElements;
        Field dexElementsField;
    }


}
